export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_TO_CART = "REMOVE_TO_CART"
export const EMPTY_TO_CART = "EMPTY_TO_CART"
export const INCRIMENT_TO_CART = "INCRIMENT_TO_CART"
export const DECRIMENT_TO_CART = "DECRIMENT_TO_CART"
export const ADD_TO_WISHLIST = "ADD_TO_WICHLIST"
export const REMOVE_TO_WISHLIST = "REMOVE_TO_WISHLIST"
export const EMPTY_TO_WISHLIST = "EMPTY_TO_WISHLIST"
export const EMPTY_WISHLIST = "EMPTY WIASHLIST"
export const WISHLIST_TO_CART = "WISHLIST_TO_CART"
export const PRODUCT_LIST = "PRODUCT_LIST"
export const PRODUCT_SET = "PRODUCT_SET"



